# Generated by Django 4.1 on 2022-08-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.JSONField(default={'state': 0})),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=56, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
