# Generated by Django 4.1 on 2022-08-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='refer_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
