# Generated by Django 4.1 on 2022-08-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0002_tguser_refer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='refer_id',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
