# Generated by Django 4.0.6 on 2022-11-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0003_alter_tguser_refer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='username',
            new_name='user_name',
        ),
    ]
