# Generated by Django 4.0.6 on 2022-11-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0004_rename_username_tguser_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user_name',
            new_name='username',
        ),
    ]
