# Generated by Django 4.0.6 on 2022-11-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0005_rename_user_name_tguser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='username',
        ),
        migrations.AddField(
            model_name='tguser',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tguser',
            name='user_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
