# Generated by Django 4.0.6 on 2022-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0006_remove_tguser_username_tguser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='ball',
            field=models.IntegerField(default=5),
        ),
    ]
