# Generated by Django 4.0.6 on 2022-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0007_tguser_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='ball',
            field=models.IntegerField(default=0),
        ),
    ]
