# Generated by Django 4.0.6 on 2022-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0008_alter_tguser_ball'),
    ]

    operations = [
        migrations.CreateModel(
            name='referal_friend',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ball', models.IntegerField(default=0)),
                ('odam', models.IntegerField(default=0)),
            ],
        ),
    ]
