# Generated by Django 4.0.6 on 2022-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0009_referal_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='odam',
            field=models.IntegerField(default=0),
        ),
    ]
