# Generated by Django 4.0.6 on 2022-11-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referer', '0010_tguser_odam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referal_friend',
            name='odam',
        ),
    ]
